version: '3.5'

services:
  rtc_db:
    container_name: rtc_db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bQ5UroNM9PqslBs}

    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    restart: on-failure
